/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include "bakery.h"
void
bakery_prog_1(char *host)
{
    CLIENT *clnt;
    struct BAKERY  *result_1;
    struct BAKERY  getn_1_arg;
    struct BAKERY  *result_2;
    struct BAKERY  proc_1_arg;
    struct BAKERY  *result_3;
    struct BAKERY  wait_1_arg;
    time_t time_numb, time_wait, time_serv;
    clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
    srand(time(NULL));
    double sleep_time = (double)rand() / RAND_MAX * 1000000 * 1.5;
    usleep(sleep_time);
    time_numb = clock();
    result_1 = getn_1(&getn_1_arg, clnt);
    if (result_1 == (struct BAKERY *) NULL) {
        clnt_perror (clnt, "call failed");
    }
    time_numb = clock() - time_numb;
    printf("getn: client pid=%2d, num=%2d\n", result_1->pid, result_1->num);
    wait_1_arg.num = result_1->num;
    wait_1_arg.pid = result_1->pid;
    sleep(rand() % 7 + 5);
    time_wait = clock();
    result_2 = wait_1(&wait_1_arg, clnt);
    if (result_2->res == '0') { 
        clnt_perror (clnt, "timeout!"); 
        clnt_destroy (clnt);
        exit (1); 
    } 
    time_wait = clock() - time_wait;
    time_serv = 0;
    double t = (double) (time_numb + time_wait + time_serv) * 1000000 / CLOCKS_PER_SEC;
    printf("proc: client pid=%2d, res=%c (sleep=%.1fs)\ntotal_time=%.4fus\n", result_2->pid, result_2->res, sleep_time / 1000000, t);
    clnt_destroy (clnt);
}
int
main (int argc, char *argv[])
{
    char *host;
    if (argc < 2) {
        printf ("usage: %s server_host\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    bakery_prog_1 (host);
    exit (0);
}
