/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct BAKERY *
getn_1(struct BAKERY *argp, CLIENT *clnt)
{
	static struct BAKERY clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETN,
		(xdrproc_t) xdr_BAKERY, (caddr_t) argp,
		(xdrproc_t) xdr_BAKERY, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct BAKERY *
wait_1(struct BAKERY *argp, CLIENT *clnt)
{
	static struct BAKERY clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, WAIT,
		(xdrproc_t) xdr_BAKERY, (caddr_t) argp,
		(xdrproc_t) xdr_BAKERY, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct BAKERY *
proc_1(struct BAKERY *argp, CLIENT *clnt)
{
	static struct BAKERY clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PROC,
		(xdrproc_t) xdr_BAKERY, (caddr_t) argp,
		(xdrproc_t) xdr_BAKERY, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
