/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct BAKERY {
	int num;
	int pid;
	int res;
};
typedef struct BAKERY BAKERY;

#define BAKERY_PROG 0x20000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETN 1
extern  struct BAKERY * getn_1(struct BAKERY *, CLIENT *);
extern  struct BAKERY * getn_1_svc(struct BAKERY *, struct svc_req *);
#define WAIT 2
extern  struct BAKERY * wait_1(struct BAKERY *, CLIENT *);
extern  struct BAKERY * wait_1_svc(struct BAKERY *, struct svc_req *);
#define PROC 3
extern  struct BAKERY * proc_1(struct BAKERY *, CLIENT *);
extern  struct BAKERY * proc_1_svc(struct BAKERY *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETN 1
extern  struct BAKERY * getn_1();
extern  struct BAKERY * getn_1_svc();
#define WAIT 2
extern  struct BAKERY * wait_1();
extern  struct BAKERY * wait_1_svc();
#define PROC 3
extern  struct BAKERY * proc_1();
extern  struct BAKERY * proc_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_BAKERY (XDR *, BAKERY*);

#else /* K&R C */
extern bool_t xdr_BAKERY ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
