1:
	gcc 1.c -o 1.out
	gcc 1_thread.c -o 1_thread.out

2:
	gcc 2.c -o 2.out
	gcc 2_1.c -o 2_1.out
	gcc 2_thread.c -o thr2.out
	gcc 2_1_thread.c -o 2_1_thread.out
	
3:
	gcc 3.c -o 3.out
	gcc 3_thread.c -o 3_thread.out

all: 1 2 3
